services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: todo_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/todo?serverVersion=8.0

  nginx:
    image: nginx:stable-alpine
    container_name: todo_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: todo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    ports:
      - "33060:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
